server:
  port: 9001
  servlet:
    context-path: /oy

spring:
  activemq:
    broker-url: tcp://119.23.187.31:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 30000
#  jms:
#    pub-sub-domain: true  # true表示top false 队列

queue.oy: oy


