server:
  port: 9001
  servlet:
    context-path: /oy

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dubbo?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai

  activemq:
    broker-url: tcp://119.23.187.31:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 30000


#  jms:
#    pub-sub-domain: true  # true表示top false 队列

queue.oy: oy


